export const CONNECTOR_NAME = 'External Marketplace Test'
export const CONNECTOR_ENDPOINT = 'https://test-vtex-app-template.free.beeceptor.com'
export const VBASE_BUCKET = 'external-mkp-test'
export const VBASE_CONFIG_BASE_PATH = 'storeConfig'
export const APP_VENDOR = 'vtex'
export const FEED_ID = '1234'
export const VTEX_APP_KEY_HEADER = 'x-vtex-api-appkey'
export const VTEX_APP_TOKEN_HEADER = 'x-vtex-api-apptoken'
