export const CONNECTOR_NAME = '{{appTitle}}'
export const CONNECTOR_ENDPOINT = '{{connectorEndpoint}}'
export const VBASE_BUCKET = '{{appName}}'
export const VBASE_CONFIG_BASE_PATH = 'storeConfig'
export const APP_VENDOR = '{{appVendor}}'
export const FEED_ID = '{{feedId}}'
