export const countryCodesData: { [code: string]: string } = {
  'ZAF': 'South Africa (ZAF)',
  'ETH': 'Ethiopia (ETH)',
  'ARE': 'U.A.E. (ARE)',
  'BHR': 'Bahrain (BHR)',
  'DZA': 'Algeria (DZA)',
  'EGY': 'Egypt (EGY)',
  'IRQ': 'Iraq (IRQ)',
  'JOR': 'Jordan (JOR)',
  'KWT': 'Kuwait (KWT)',
  'LBN': 'Lebanon (LBN)',
  'LBY': 'Libya (LBY)',
  'MAR': 'Morocco (MAR)',
  'OMN': 'Oman (OMN)',
  'QAT': 'Qatar (QAT)',
  'SAU': 'Saudi Arabia (SAU)',
  'SYR': 'Syria (SYR)',
  'TUN': 'Tunisia (TUN)',
  'YEM': 'Yemen (YEM)',
  'CHL': 'Chile (CHL)',
  'IND': 'India (IND)',
  'AZE': 'Azerbaijan (AZE)',
  'RUS': 'Russia (RUS)',
  'BLR': 'Belarus (BLR)',
  'BGR': 'Bulgaria (BGR)',
  'BGD': 'Bangladesh (BGD)',
  'CHN': 'China (CHN)',
  'FRA': 'France (FRA)',
  'BIH': 'Bosnia and Herzegovina (BIH)',
  'ESP': 'Spain (ESP)',
  'USA': 'United States (USA)',
  'CZE': 'Czech Republic (CZE)',
  'GBR': 'United Kingdom (GBR)',
  'DNK': 'Denmark (DNK)',
  'AUT': 'Austria (AUT)',
  'CHE': 'Switzerland (CHE)',
  'DEU': 'Germany (DEU)',
  'LIE': 'Liechtenstein (LIE)',
  'LUX': 'Luxembourg (LUX)',
  'MDV': 'Maldives (MDV)',
  'GRC': 'Greece (GRC)',
  'AUS': 'Australia (AUS)',
  'BLZ': 'Belize (BLZ)',
  'CAN': 'Canada (CAN)',
  'HKG': 'Hong Kong (HKG)',
  'IRL': 'Ireland (IRL)',
  'JAM': 'Jamaica (JAM)',
  'MYS': 'Malaysia (MYS)',
  'NZL': 'New Zealand (NZL)',
  'PHL': 'Philippines (PHL)',
  'SGP': 'Singapore (SGP)',
  'TTO': 'Trinidad and Tobago (TTO)',
  'ZWE': 'Zimbabwe (ZWE)',
  'ARG': 'Argentina (ARG)',
  'BOL': 'Bolivia (BOL)',
  'COL': 'Colombia (COL)',
  'CRI': 'Costa Rica (CRI)',
  'DOM': 'Dominican Republic (DOM)',
  'ECU': 'Ecuador (ECU)',
  'GTM': 'Guatemala (GTM)',
  'HND': 'Honduras (HND)',
  'MEX': 'Mexico (MEX)',
  'NIC': 'Nicaragua (NIC)',
  'PAN': 'Panama (PAN)',
  'PER': 'Peru (PER)',
  'PRI': 'Puerto Rico (PRI)',
  'PRY': 'Paraguay (PRY)',
  'SLV': 'El Salvador (SLV)',
  'URY': 'Uruguay (URY)',
  'VEN': 'Bolivarian Republic of Venezuela (VEN)',
  'EST': 'Estonia (EST)',
  'IRN': 'Iran (IRN)',
  'SEN': 'Senegal (SEN)',
  'FIN': 'Finland (FIN)',
  'FRO': 'Faroe Islands (FRO)',
  'BEL': 'Belgium (BEL)',
  'COD': 'Congo [DRC] (COD)',
  'CIV': 'Ivory Coast (CIV)',
  'CMR': 'Cameroon (CMR)',
  'HTI': 'Haiti (HTI)',
  'MCO': 'Principality of Monaco (MCO)',
  'MLI': 'Mali (MLI)',
  'REU': 'Réunion (REU)',
  'NLD': 'Netherlands (NLD)',
  'NGA': 'Nigeria (NGA)',
  'ISR': 'Israel (ISR)',
  'HRV': 'Croatia (HRV)',
  'HUN': 'Hungary (HUN)',
  'ARM': 'Armenia (ARM)',
  'IDN': 'Indonesia (IDN)',
  'ISL': 'Iceland (ISL)',
  'ITA': 'Italy (ITA)',
  'JPN': 'Japan (JPN)',
  'GEO': 'Georgia (GEO)',
  'KAZ': 'Kazakhstan (KAZ)',
  'GRL': 'Greenland (GRL)',
  'KHM': 'Cambodia (KHM)',
  'KOR': 'Korea (KOR)',
  'KGZ': 'Kyrgyzstan (KGZ)',
  'LAO': 'Lao PDR (LAO)',
  'LTU': 'Lithuania (LTU)',
  'LVA': 'Latvia (LVA)',
  'MKD': 'Macedonia (Former Yugoslav Republic of Macedonia) (MKD)',
  'MNG': 'Mongolia (MNG)',
  'BRN': 'Brunei Darussalam (BRN)',
  'MLT': 'Malta (MLT)',
  'MMR': 'Myanmar (MMR)',
  'NOR': 'Norway (NOR)',
  'NPL': 'Nepal (NPL)',
  'PAK': 'Pakistan (PAK)',
  'POL': 'Poland (POL)',
  'AFG': 'Afghanistan (AFG)',
  'BRA': 'Brazil (BRA)',
  'PRT': 'Portugal (PRT)',
  'MDA': 'Moldova (MDA)',
  'ROU': 'Romania (ROU)',
  'RWA': 'Rwanda (RWA)',
  'SWE': 'Sweden (SWE)',
  'LKA': 'Sri Lanka (LKA)',
  'SVK': 'Slovakia (SVK)',
  'SVN': 'Slovenia (SVN)',
  'SOM': 'Somalia (SOM)',
  'ALB': 'Albania (ALB)',
  'SCG': 'Serbia and Montenegro (Former) (SCG)',
  'MNE': 'Montenegro (MNE)',
  'SRB': 'Serbia (SRB)',
  'KEN': 'Kenya (KEN)',
  'TAJ': 'Tajikistan (TAJ)',
  'THA': 'Thailand (THA)',
  'ERI': 'Eritrea (ERI)',
  'TKM': 'Turkmenistan (TKM)',
  'BWA': 'Botswana (BWA)',
  'TUR': 'Turkey (TUR)',
  'UKR': 'Ukraine (UKR)',
  'UZB': 'Uzbekistan (UZB)',
  'VNM': 'Vietnam (VNM)',
  'MAC': 'Macao SAR (MAC)',
  'TWN': 'Taiwan (TWN)',
}
