export const cultureInfoData: { [code: string]: string } = {
  'af-ZA': 'South Africa (af-ZA)',
  'am-ET': 'Ethiopia (am-ET)',
  'ar-AE': 'U.A.E. (ar-AE)',
  'ar-BH': 'Bahrain (ar-BH)',
  'ar-DZ': 'Algeria (ar-DZ)',
  'ar-EG': 'Egypt (ar-EG)',
  'ar-IQ': 'Iraq (ar-IQ)',
  'ar-JO': 'Jordan (ar-JO)',
  'ar-KW': 'Kuwait (ar-KW)',
  'ar-LB': 'Lebanon (ar-LB)',
  'ar-LY': 'Libya (ar-LY)',
  'ar-MA': 'Morocco (ar-MA)',
  'ar-OM': 'Oman (ar-OM)',
  'ar-QA': 'Qatar (ar-QA)',
  'ar-SA': 'Saudi Arabia (ar-SA)',
  'ar-SY': 'Syria (ar-SY)',
  'ar-TN': 'Tunisia (ar-TN)',
  'ar-YE': 'Yemen (ar-YE)',
  'arn-CL': 'Chile (arn-CL)',
  'as-IN': 'India (as-IN)',
  'az-Cyrl-AZ': 'Azerbaijan (az-Cyrl-AZ)',
  'az-Latn-AZ': 'Azerbaijan (az-Latn-AZ)',
  'ba-RU': 'Russia (ba-RU)',
  'be-BY': 'Belarus (be-BY)',
  'bg-BG': 'Bulgaria (bg-BG)',
  'bn-BD': 'Bangladesh (bn-BD)',
  'bn-IN': 'India (bn-IN)',
  'bo-CN': 'China (bo-CN)',
  'br-FR': 'France (br-FR)',
  'bs-Cyrl-BA': 'Bosnia and Herzegovina (bs-Cyrl-BA)',
  'bs-Latn-BA': 'Bosnia and Herzegovina (bs-Latn-BA)',
  'ca-ES': 'Spain (ca-ES)',
  'ca-ES-valencia': 'Spain (ca-ES-valencia)',
  'chr-Cher-US': 'United States (chr-Cher-US)',
  'co-FR': 'France (co-FR)',
  'cs-CZ': 'Czech Republic (cs-CZ)',
  'cy-GB': 'United Kingdom (cy-GB)',
  'da-DK': 'Denmark (da-DK)',
  'de-AT': 'Austria (de-AT)',
  'de-CH': 'Switzerland (de-CH)',
  'de-DE': 'Germany (de-DE)',
  'de-LI': 'Liechtenstein (de-LI)',
  'de-LU': 'Luxembourg (de-LU)',
  'dsb-DE': 'Germany (dsb-DE)',
  'dv-MV': 'Maldives (dv-MV)',
  'el-GR': 'Greece (el-GR)',
  'en-029': 'Caribbean (en-029)',
  'en-AU': 'Australia (en-AU)',
  'en-BZ': 'Belize (en-BZ)',
  'en-CA': 'Canada (en-CA)',
  'en-GB': 'United Kingdom (en-GB)',
  'en-HK': 'Hong Kong (en-HK)',
  'en-IE': 'Ireland (en-IE)',
  'en-IN': 'India (en-IN)',
  'en-JM': 'Jamaica (en-JM)',
  'en-MY': 'Malaysia (en-MY)',
  'en-NZ': 'New Zealand (en-NZ)',
  'en-PH': 'Philippines (en-PH)',
  'en-SG': 'Singapore (en-SG)',
  'en-TT': 'Trinidad and Tobago (en-TT)',
  'en-US': 'United States (en-US)',
  'en-ZA': 'South Africa (en-ZA)',
  'en-ZW': 'Zimbabwe (en-ZW)',
  'es-419': 'Latin America (es-419)',
  'es-AR': 'Argentina (es-AR)',
  'es-BO': 'Bolivia (es-BO)',
  'es-CL': 'Chile (es-CL)',
  'es-CO': 'Colombia (es-CO)',
  'es-CR': 'Costa Rica (es-CR)',
  'es-DO': 'Dominican Republic (es-DO)',
  'es-EC': 'Ecuador (es-EC)',
  'es-ES': 'Spain (es-ES)',
  'es-GT': 'Guatemala (es-GT)',
  'es-HN': 'Honduras (es-HN)',
  'es-MX': 'Mexico (es-MX)',
  'es-NI': 'Nicaragua (es-NI)',
  'es-PA': 'Panama (es-PA)',
  'es-PE': 'Peru (es-PE)',
  'es-PR': 'Puerto Rico (es-PR)',
  'es-PY': 'Paraguay (es-PY)',
  'es-SV': 'El Salvador (es-SV)',
  'es-US': 'United States (es-US)',
  'es-UY': 'Uruguay (es-UY)',
  'es-VE': 'Bolivarian Republic of Venezuela (es-VE)',
  'et-EE': 'Estonia (et-EE)',
  'eu-ES': 'Spain (eu-ES)',
  'fa-IR': 'Iran (fa-IR)',
  'ff-Latn-SN': 'Senegal (ff-Latn-SN)',
  'fi-FI': 'Finland (fi-FI)',
  'fil-PH': 'Philippines (fil-PH)',
  'fo-FO': 'Faroe Islands (fo-FO)',
  'fr-BE': 'Belgium (fr-BE)',
  'fr-CA': 'Canada (fr-CA)',
  'fr-CD': 'Congo [DRC] (fr-CD)',
  'fr-CH': 'Switzerland (fr-CH)',
  'fr-CI': 'Ivory Coast (fr-CI)',
  'fr-CM': 'Cameroon (fr-CM)',
  'fr-FR': 'France (fr-FR)',
  'fr-HT': 'Haiti (fr-HT)',
  'fr-LU': 'Luxembourg (fr-LU)',
  'fr-MA': 'Morocco (fr-MA)',
  'fr-MC': 'Principality of Monaco (fr-MC)',
  'fr-ML': 'Mali (fr-ML)',
  'fr-RE': 'Réunion (fr-RE)',
  'fr-SN': 'Senegal (fr-SN)',
  'fy-NL': 'Netherlands (fy-NL)',
  'ga-IE': 'Ireland (ga-IE)',
  'gd-GB': 'United Kingdom (gd-GB)',
  'gl-ES': 'Spain (gl-ES)',
  'gn-PY': 'Paraguay (gn-PY)',
  'gsw-FR': 'France (gsw-FR)',
  'gu-IN': 'India (gu-IN)',
  'ha-Latn-NG': 'Nigeria (ha-Latn-NG)',
  'haw-US': 'United States (haw-US)',
  'he-IL': 'Israel (he-IL)',
  'hi-IN': 'India (hi-IN)',
  'hr-BA': 'Bosnia and Herzegovina (hr-BA)',
  'hr-HR': 'Croatia (hr-HR)',
  'hsb-DE': 'Germany (hsb-DE)',
  'hu-HU': 'Hungary (hu-HU)',
  'hy-AM': 'Armenia (hy-AM)',
  'id-ID': 'Indonesia (id-ID)',
  'ig-NG': 'Nigeria (ig-NG)',
  'ii-CN': 'China (ii-CN)',
  'is-IS': 'Iceland (is-IS)',
  'it-CH': 'Switzerland (it-CH)',
  'it-IT': 'Italy (it-IT)',
  'iu-Cans-CA': 'Canada (iu-Cans-CA)',
  'iu-Latn-CA': 'Canada (iu-Latn-CA)',
  'ja-JP': 'Japan (ja-JP)',
  'jv-Latn-ID': 'Indonesia (jv-Latn-ID)',
  'ka-GE': 'Georgia (ka-GE)',
  'kk-KZ': 'Kazakhstan (kk-KZ)',
  'kl-GL': 'Greenland (kl-GL)',
  'km-KH': 'Cambodia (km-KH)',
  'kn-IN': 'India (kn-IN)',
  'ko-KR': 'Korea (ko-KR)',
  'kok-IN': 'India (kok-IN)',
  'ku-Arab-IQ': 'Iraq (ku-Arab-IQ)',
  'ky-KG': 'Kyrgyzstan (ky-KG)',
  'lb-LU': 'Luxembourg (lb-LU)',
  'lo-LA': 'Lao PDR (lo-LA)',
  'lt-LT': 'Lithuania (lt-LT)',
  'lv-LV': 'Latvia (lv-LV)',
  'mg-MG': 'Indonesia (mg-MG)',
  'mi-NZ': 'New Zealand (mi-NZ)',
  'mk-MK': 'Macedonia (Former Yugoslav Republic of Macedonia) (mk-MK)',
  'ml-IN': 'India (ml-IN)',
  'mn-MN': 'Mongolia (mn-MN)',
  'mn-Mong-CN': 'China (mn-Mong-CN)',
  'mn-Mong-MN': 'Mongolia (mn-Mong-MN)',
  'moh-CA': 'Canada (moh-CA)',
  'mr-IN': 'India (mr-IN)',
  'ms-BN': 'Brunei Darussalam (ms-BN)',
  'ms-MY': 'Malaysia (ms-MY)',
  'mt-MT': 'Malta (mt-MT)',
  'my-MM': 'Myanmar (my-MM)',
  'nb-NO': 'Norway (nb-NO)',
  'ne-IN': 'India (ne-IN)',
  'ne-NP': 'Nepal (ne-NP)',
  'nl-BE': 'Belgium (nl-BE)',
  'nl-NL': 'Netherlands (nl-NL)',
  'nn-NO': 'Norway (nn-NO)',
  'nqo-GN': 'Indonesia (nqo-GN)',
  'nso-ZA': 'South Africa (nso-ZA)',
  'oc-FR': 'France (oc-FR)',
  'om-ET': 'Ethiopia (om-ET)',
  'or-IN': 'India (or-IN)',
  'pa-Arab-PK': 'Pakistan (pa-Arab-PK)',
  'pa-IN': 'India (pa-IN)',
  'pl-PL': 'Poland (pl-PL)',
  'prs-AF': 'Afghanistan (prs-AF)',
  'ps-AF': 'Afghanistan (ps-AF)',
  'pt-AO': 'Indonesia (pt-AO)',
  'pt-BR': 'Brazil (pt-BR)',
  'pt-PT': 'Portugal (pt-PT)',
  'qut-GT': 'Guatemala (qut-GT)',
  'quz-BO': 'Bolivia (quz-BO)',
  'quz-EC': 'Ecuador (quz-EC)',
  'quz-PE': 'Peru (quz-PE)',
  'rm-CH': 'Switzerland (rm-CH)',
  'ro-MD': 'Moldova (ro-MD)',
  'ro-RO': 'Romania (ro-RO)',
  'ru-RU': 'Russia (ru-RU)',
  'rw-RW': 'Rwanda (rw-RW)',
  'sa-IN': 'India (sa-IN)',
  'sah-RU': 'Russia (sah-RU)',
  'sd-Arab-PK': 'Pakistan (sd-Arab-PK)',
  'se-FI': 'Finland (se-FI)',
  'se-NO': 'Norway (se-NO)',
  'se-SE': 'Sweden (se-SE)',
  'si-LK': 'Sri Lanka (si-LK)',
  'sk-SK': 'Slovakia (sk-SK)',
  'sl-SI': 'Slovenia (sl-SI)',
  'sma-NO': 'Norway (sma-NO)',
  'sma-SE': 'Sweden (sma-SE)',
  'smj-NO': 'Norway (smj-NO)',
  'smj-SE': 'Sweden (smj-SE)',
  'smn-FI': 'Finland (smn-FI)',
  'sms-FI': 'Finland (sms-FI)',
  'sn-Latn-ZW': 'Indonesia (sn-Latn-ZW)',
  'so-SO': 'Somalia (so-SO)',
  'sq-AL': 'Albania (sq-AL)',
  'sr-Cyrl-BA': 'Bosnia and Herzegovina (sr-Cyrl-BA)',
  'sr-Cyrl-CS': 'Serbia and Montenegro (Former) (sr-Cyrl-CS)',
  'sr-Cyrl-ME': 'Montenegro (sr-Cyrl-ME)',
  'sr-Cyrl-RS': 'Serbia (sr-Cyrl-RS)',
  'sr-Latn-BA': 'Bosnia and Herzegovina (sr-Latn-BA)',
  'sr-Latn-CS': 'Serbia and Montenegro (Former) (sr-Latn-CS)',
  'sr-Latn-ME': 'Montenegro (sr-Latn-ME)',
  'sr-Latn-RS': 'Serbia (sr-Latn-RS)',
  'st-ZA': 'South Africa (st-ZA)',
  'sv-FI': 'Finland (sv-FI)',
  'sv-SE': 'Sweden (sv-SE)',
  'sw-KE': 'Kenya (sw-KE)',
  'syr-SY': 'Syria (syr-SY)',
  'ta-IN': 'India (ta-IN)',
  'ta-LK': 'Sri Lanka (ta-LK)',
  'te-IN': 'India (te-IN)',
  'tg-Cyrl-TJ': 'Tajikistan (tg-Cyrl-TJ)',
  'th-TH': 'Thailand (th-TH)',
  'ti-ER': 'Eritrea (ti-ER)',
  'ti-ET': 'Ethiopia (ti-ET)',
  'tk-TM': 'Turkmenistan (tk-TM)',
  'tn-BW': 'Botswana (tn-BW)',
  'tn-ZA': 'South Africa (tn-ZA)',
  'tr-TR': 'Turkey (tr-TR)',
  'ts-ZA': 'South Africa (ts-ZA)',
  'tt-RU': 'Russia (tt-RU)',
  'tzm-Latn-DZ': 'Algeria (tzm-Latn-DZ)',
  'tzm-Tfng-MA': 'Morocco (tzm-Tfng-MA)',
  'ug-CN': 'China (ug-CN)',
  'uk-UA': 'Ukraine (uk-UA)',
  'ur-IN': 'India (ur-IN)',
  'ur-PK': 'Pakistan (ur-PK)',
  'uz-Cyrl-UZ': 'Uzbekistan (uz-Cyrl-UZ)',
  'uz-Latn-UZ': 'Uzbekistan (uz-Latn-UZ)',
  'vi-VN': 'Vietnam (vi-VN)',
  'wo-SN': 'Senegal (wo-SN)',
  'xh-ZA': 'South Africa (xh-ZA)',
  'yo-NG': 'Nigeria (yo-NG)',
  'zgh-Tfng-MA': 'Indonesia (zgh-Tfng-MA)',
  'zh-CN': 'China (zh-CN)',
  'zh-HK': 'Hong Kong SAR (zh-HK)',
  'zh-MO': 'Macao SAR (zh-MO)',
  'zh-SG': 'Singapore (zh-SG)',
  'zh-TW': 'Taiwan (zh-TW)',
  'zu-ZA': 'South Africa (zu-ZA)',
}
