export const currencyCodesData: { [code: string]: string } = {
  ZAR: 'South African Rand (ZAR)',
  ETB: 'Ethiopian Birr (ETB)',
  AED: 'UAE Dirham (AED)',
  BHD: 'Bahraini Dinar (BHD)',
  DZD: 'Algerian Dinar (DZD)',
  EGP: 'Egyptian Pound (EGP)',
  IQD: 'Iraqi Dinar (IQD)',
  JOD: 'Jordanian Dinar (JOD)',
  KWD: 'Kuwaiti Dinar (KWD)',
  LBP: 'Lebanese Pound (LBP)',
  LYD: 'Libyan Dinar (LYD)',
  MAD: 'Moroccan Dirham (MAD)',
  OMR: 'Omani Rial (OMR)',
  QAR: 'Qatari Rial (QAR)',
  SAR: 'Saudi Riyal (SAR)',
  SYP: 'Syrian Pound (SYP)',
  TND: 'Tunisian Dinar (TND)',
  YER: 'Yemeni Rial (YER)',
  CLP: 'Chilean Peso (CLP)',
  INR: 'Indian Rupee (INR)',
  AZN: 'Azerbaijani Manat (AZN)',
  RUB: 'Russian Ruble (RUB)',
  BYN: 'Belarusian Ruble (BYN)',
  BGN: 'Bulgarian Lev (BGN)',
  BDT: 'Bangladeshi Taka (BDT)',
  CNY: 'PRC Renminbi (CNY)',
  EUR: 'Euro (EUR)',
  BAM: 'Convertible Marks (BAM)',
  USD: 'US Dollar (USD)',
  CZK: 'Czech Koruna (CZK)',
  GBP: 'UK Pound Sterling (GBP)',
  DKK: 'Danish Krone (DKK)',
  CHF: 'Swiss Franc (CHF)',
  MVR: 'Rufiyaa (MVR)',
  XCD: 'Eastern Caribbean Dollar (XCD)',
  AUD: 'Australian Dollar (AUD)',
  BZD: 'Belize Dollar (BZD)',
  CAD: 'Canadian Dollar (CAD)',
  HKD: 'Hong Kong Dollar (HKD)',
  JMD: 'Jamaican Dollar (JMD)',
  MYR: 'Malaysian Ringgit (MYR)',
  NZD: 'New Zealand Dollar (NZD)',
  PHP: 'Philippine Peso (PHP)',
  SGD: 'Singapore Dollar (SGD)',
  TTD: 'Trinidad Dollar (TTD)',
  ARS: 'Argentine Peso (ARS)',
  BOB: 'Boliviano (BOB)',
  COP: 'Colombian Peso (COP)',
  CRC: 'Costa Rican Colon (CRC)',
  DOP: 'Dominican Peso (DOP)',
  GTQ: 'Guatemalan Quetzal (GTQ)',
  HNL: 'Honduran Lempira (HNL)',
  MXN: 'Mexican Peso (MXN)',
  NIO: 'Cordoba (NIO)',
  PAB: 'Panamanian Balboa (PAB)',
  PEN: 'Peruvian Nuevo Sol (PEN)',
  PYG: 'Paraguay Guarani (PYG)',
  UYU: 'Peso Uruguayo (UYU)',
  VES: 'Venezuelan Bolívar (VES)',
  IRR: 'Iranian Rial (IRR)',
  XOF: 'CFA (XOF)',
  CDF: 'Congolese Franc (CDF)',
  XAF: 'CFA Franc BEAC (XAF)',
  HTG: 'Haitian Gourde (HTG)',
  NGN: 'Nigerian Naira (NGN)',
  ILS: 'Israeli New Shekel (ILS)',
  HRK: 'Croatian Kuna (HRK)',
  HUF: 'Hungarian Forint (HUF)',
  AMD: 'Armenian Dram (AMD)',
  IDR: 'Indonesian Rupiah (IDR)',
  ISK: 'Icelandic Krona (ISK)',
  JPY: 'Japanese Yen (JPY)',
  GEL: 'Lari (GEL)',
  KZT: 'Tenge (KZT)',
  KHR: 'Riel (KHR)',
  KRW: 'Korean Won (KRW)',
  KGS: 'som (KGS)',
  LAK: 'Kip (LAK)',
  MKD: 'Macedonian Denar (MKD)',
  MNT: 'Tugrik (MNT)',
  BND: 'Brunei Dollar (BND)',
  MMK: 'Myanmar Kyat (MMK)',
  NOK: 'Norwegian Krone (NOK)',
  NPR: 'Nepalese Rupees (NPR)',
  PKR: 'Pakistan Rupee (PKR)',
  PLN: 'Polish Zloty (PLN)',
  AFN: 'Afghani (AFN)',
  BRL: 'Real (BRL)',
  MDL: 'Moldovan Leu (MDL)',
  RON: 'Romanian Leu (RON)',
  RWF: 'Rwandan Franc (RWF)',
  SEK: 'Swedish Krona (SEK)',
  LKR: 'Sri Lanka Rupee (LKR)',
  SOS: 'Somali Shilling (SOS)',
  ALL: 'Albanian Lek (ALL)',
  RSD: 'Serbian Dinar (RSD)',
  KES: 'Kenyan Shilling (KES)',
  TJS: 'Somoni (TJS)',
  THB: 'Thai Baht (THB)',
  ERN: 'Eritrean Nakfa (ERN)',
  TMT: 'Turkmen manat (TMT)',
  BWP: 'Pula (BWP)',
  TRY: 'Turkish Lira (TRY)',
  UAH: 'Ukrainian Hryvnia (UAH)',
  UZS: 'Uzbekistan Som (UZS)',
  VND: 'Vietnamese Dong (VND)',
  MOP: 'Macao Pataca (MOP)',
  TWD: 'New Taiwan Dollar (TWD)',
}
